package patterns

var Patterns = map[string]string{
	`HttpUrl`:                `\bhttps?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)\b$`,
	`AwsArn`:                 `\barn:([^:\n]*):([^:\n]*):([^:\n]*):([^:\n]*):(([^:\/\n]*)[:\/])?(.*)\b$`,
	`AwsS3Bucket`:            `([a-z0-9.-]+\.s3\.amazonaws\.com|s3\.amazonaws\.com/[a-z0-9._\-]+)`,
	`AwsIamAccessId`:         `AKIA[0-9A-Z]{16}`,
	`AwsSecretKey`:           `(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]`,
	`GitRepo`:                `\b(https?://)?github\.com(?:\/[^\s\/]+){2}\b$`,
	`Date`:                   `\b\d{2}[/-]\d{2}[/-]\d{2,4}\b$`,
	`Jwt`:                    `\beyJ[A-Za-z0-9-_=]+\.eyJ[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*\b$`,
	`UsAddress`:              `\b(\d+ [^,]+, [A-Z]{2} \d{5})\b$`,
	`IpAddrV4`:               `\b(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}\b$`,
	`IpAddrV6`:               `\b(?<![:.\w])(?:[A-F0-9]{1,4}:){7}[A-F0-9]{1,4}(?![:.\w])\b$`,
	`MacAddress`:             `([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})`,
	`Sid`:                    `\bS-\d-\d+-(\d+-){1,14}\d+\b$`,
	`Md5`:                    `\b[a-f0-9]{32}\b$`,
	`Sha256`:                 `\b[A-Fa-f0-9]{64}\b$`,
	`Sha512`:                 `\b[A-Fa-f0-9]{128}\b$`,
	`EmailAddr`:              `\S+@\S+\.\S+$`,
	`PhoneNumber`:            `(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$`,
	`Ssn`:                    `(?!666|000|9\d{2})\d{3}-(?!00)\d{2}-(?!0{4})\d{4}$`,
	`SlackApiKey`:            `xox[baprs]-[0-9]{12}-[0-9]{12}-[0-9a-zA-Z]{24}`,
	`SlackAccessToken`:       `T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}`,
	`SlackWebHook`:           `https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}`,
	`MailGunApiKey`:          `[0-9a-f]{32}-us[0-9]{1,2}`,
	`MailChimpKey`:           `[0-9a-f]{32}-us[0-9]{1,2}`,
	`GoogleApiKey`:           `AIza[0-9A-Za-z\\-_]{35}`,
	`FacebookToken`:          `EAACEdEose0cBA[0-9A-Za-z]+`,
	`Version`:                `\b(v(ersion)*\s*)([0-9]+)\.([0-9]+)\.([0-9]+)(?:\.([0-9]+))?\b$`,
	`WindowsPath`:            `(?:[a-zA-Z]\:|\\\\[\w\.]+\\[\w.$]+)\\(?:[\w]+\\)*\w([\w.])+$`,
	`TwilioApiKey`:           `SK[0-9a-fA-F]{32}$`,
	`Guid`:                   `[{]?[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}[}]?$`,
	`Coordinates`:            `[-+]?([1-8]?\d(\.\d+)?|90(\.0+)?),\s*[-+]?(180(\.0+)?|((1[0-7]\d)|([1-9]?\d))(\.\d+)?)$`,
	`SquareAccessToken`:      `sqOatp-[0-9A-Za-z\\-_]{22}`,
	`SquareOauthSecret`:      `sq0csp-[ 0-9A-Za-z\\-_]{43}`,
	`AzureSubscriptionId`:    `[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$`,
	`AzureStorageKey`:        `AccountKey=[a-zA-Z0-9+\/=]{88}`,
	`WapBssid`:               `([0-9A-F]{2}([:-]|$)){6}`,
	`WindowsVersion`:         `(Windows (7|8(\.1)?|3(\.1|\.0)|10|ME|XP|Vista|95|98|2000|1\.0[1-4]|2\.(03|1[0|1])))$`,
	`EnvironmentVariable`:    `[A-Z_]+=[\w\d]+\s?$`,
	`NetworkShare`:           `(\\)(\\[\w\.-_]+){2,}(\\?)$`,
	`GitHubSecret`:           `github.*['|\"][0-9a-zA-Z]{35,40}['|\"]`,
	`HerokuKeys`:             `heroku.*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}`,
	`PayPalToken`:            `access_token\\$production\\$[0-9a-z]{16}\\$[0-9a-f]{32}`,
	`AsymmetricKeyHeader`:    `\\-\\-\\-\\-\\-BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?\\-\\-\\-\\-\\-`,
	`AmsAuthToken`:           `amzn.mws.[0-9a-f]{8}-[0-9a-f]{4}-10-9a-f1{4}-[0-9a,]{4}-[0-9a-f]{12}`,
	`PicaticApiKey`:          `sk_live_[0-9a-z]{32}`,
	`TwitterAccessToken`:     `[1-9][ 0-9]+-[0-9a-zA-Z]{40}`,
	`AuthorizationBasic`:     `(?i)Authorization: Basic [a-zA-Z0-9_\-.=]+\s?`,
	`AuthorizationBearer`:    `(?i)Authorization: Bearer [a-zA-Z0-9_\-.=]+\s?`,
	`GenericApiKey`:          `(?i)(api_key|apikey)(.{0,20})?['|"][0-9a-zA-Z]{32,45}['|"]`,
	`GenericSecret`:          `(?i)secret(.{0,20})?['|"][0-9a-zA-Z]{32,45}['|"]`,
	`WindowsRegistryKey`:     `(?i)^(HKEY_LOCAL_MACHINE|HKLM)([a-zA-Z0-9\s_@-\^!#.:/$%&+={}\[\]*])+$`,
	`VariableDeclaration`:    `\s?[\w_\-]+\s?:?[=]{1}\s?["']?[\d\w\s]+["']?\s?`,
	`HTMLComment`:            `<!--(.*?)-->`,
	`AwsS3AccessLog`:         `(\S+) (\S+) \[(.*?)\] (\S+) (\S+) (\S+) (\S+) (\S+) "([^"]+)" (\S+) (\S+) (\S+) (\S+) (\S+) (\S+) "([^"]+)" "([^"]+)"`,
	`ApacheLog`:              `(\S+) (\S+) (\S+) \[([\w:/]+\s[+\-]\d{4})\] "(\S+)\s?(\S+)?\s?(\S+)?" (\d{3}|-) (\d+|-)\s?"?([^"]*)"?\s?"?([^"]*)?"?$`,
	`WindowsIISLog`:          `(\d{4}\-\d{2}\-\d{2}\s+)(\d{2}\:\d{2}\:\d{2}\s+)(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\s+)(.+?\s+)(.+?\s+)(.+?\s+)(\d{1,3}\s+)(.+?\s+)(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\s+)(.+?\s+)(\d{1,3}\s+)(\d{1,3}\s+)(\d+\s+)(\d+\s+)(\d+\s+)(\d+)?\s?`,
	`SyslogRfc3164`:          `\<([0-9]{1,3})\>([A-Za-z]{3} [0-9]{1,2} \d{2}:\d{2}:\d{2}) ([\S]+) ([\S\s]+)`,
	`SyslogRfc5424`:          `<(\d|\d{2}|1[1-8]\d|19[01])>(\d{1,2})\s(-|([12]\d{3})-(0\d|[1][012])-([012]\d|3[01])T([01]\d|2[0-4]):([0-5]\d):([0-5]\d|60)(?:\.(\d{1,6}))?(Z|[+-]\d{2}:\d{2}))\s([\S]{1,255})\s([\S]{1,48})\s([\S]{1,128})\s([\S]{1,32})\s(-|(?:\[.+?(?<!\\)\])+)(?:\s(.+))?\s?`,
	`NginxLog`:               `([^ ]*) - ([^ ]*) \[(.*)\] \"([^ ]*) ([^ ]*) ([^ ]*)\" (-|[0-9]*) (-|[0-9]*) \"(.+?|-)\" ([^ ]*|-) ([^ ]*|-) ([^ ]*|-) \"(.+?|-)\" \"(.+?|-)\" \"(.+?|-)\"\s?`,
	`CVE`:                    `CVE-\d{4}-\d{4,7}\s?`,
	`CVSSv2`:                 `(AV:([LAN])\/AC:([HML])\/Au:([NSM])\/C:([NPC])\/I:([NPC])\/A:([NPC])(?:\/E:(ND|U|POC|F|H)\/RL:(ND|OF|T|W|U)\/RC:(ND|UC|UR|C)(?:\/CDP:(N|L|LM|MH|H|ND)\/TD:(N|L|M|H|ND)\/CR:(L|M|H|ND)\/IR:(L|M|H|ND)\/AR:(L|M|H|ND))?)?)`,
	`CVSSv3`:                 `/AV:[NALP]/AC:[LH]/PR:[NLH]/UI:[NR]/S:[UC]/C:[NLH]/I:[NLH]/A:[NLH]`,
	`CVSSv3.1`:               `/AV:[NALP]/AC:[LH]/PR:[NLH]/UI:[NR]/S:[UC]/C:[NLH]/I:[NLH]/A:[NLH]/E:[F|H|U|P|X]/RL:[W|U|T|O|X]/RC:[C|R|U|X]/CR:[X|L|M|H]/IR:[X|L|M|H]/AR:[X|L|M|H]/MAV:[X|N|A|L|P]/MAC:[X|L|H]/MPR:[X|N|L|H]/MUI:[X|N|R]/MS:[X|U|C]/MC:[X|N|L|H]/MI:[X|N|L|H]/MA:[X|N|L|H]`,
	`PowerShellbase64Hidden`: `(?i)powershell.exe.*Hidden.*Enc\s[\w]+\s?`,
	`CmdExec`:                `(?i)^cmd\.exe \\c\s[\w\d"'*&\^%$#@!:./(),.\/+=|\\{}<>:; ]+\s?`,
	`TwitterHandle`:          `@([A-Za-z0-9_]{1,15})$`,
	`FacebookPageUrl`:        `(?:http:\/\/)?(?:www\.)?facebook\.com\/(?:(?:\w)*#!\/)?(?:pages\/)?(?:[\w\-]*\/)*([\w\-]*)`,
	`HTTPRequest`:            `GET\s+([^?\s]+)((?:[?&][^&\s]+)*)\s+(HTTP/.*)`,
	`HostHeader`:             `Host: (.+)\r\n`,
	`HTML`:                   `^<.*>.*</.*>\s?`,
	`YoutubeVideo`:           `((https(?:s)?:\/\/)?(www\.)?)?(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?&v=))((?:\w|-){11})((?:\&|\?)\S*)?`,
	`Log4jLog`:               `(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) (\S*) (\S*) (\S*):(\d*) - (.*)`,
	`AwsElbAccessLog`:        `(\S+)\s+\S+\s+\S+\s+\S+\s+\S+\s+\S+\s+\S+\s+\S+\s+([^"]+)\s+\S+\s+\S+\s+"([^"]+)\s+HTTP\/\d.\d"\s+"([^"]+)"\s+-\s+-$`,
	`AkamaiLog`:              `([\d\.]+)\s([\w\-]+)\s([\w\-]+)\s\[(\d+\/\w+\/\d+\:\d+\:\d+\:\d+\s\+\d+)\]\s"(.+?)"\s([\d\-]+)\s([\d\-]+)\s"(.+?)"\s"(.+?)"\s"(.+?)"\s"(.+?)"\s"(.+?)"`,
	`EthereumAddress`:        `0x([a-zA-Z0-9]{40})\s?`,
	`PgpFingerPrint`:         `(([a-fA-F0-9]{4}\ ){9}[a-fA-F0-9]{4})\s?`,
	`NameSpace`:              `\\\\\.\\.*/s?`,
	`SePrivilege`:            `Se[A-Z][A-z]+Privilege/s?`,
	`UserAgent`:              `[\w\-]+\/[\w\-]+\.[\w\-]+(?:\.[\w\-])* ?(?:\[[a-z]{2}\] )?\((?:.+[:;\-].+|[+ ]?http://.+)\)\s?`,
	`SQLQuery`:               `(?i)SELECT\s.*FROM\s.*WHERE\s.*[;\s]?`,
	`LinkedInClientID`:       `(?i)linkedin(.{0,20})?(?-i)['\"][0-9a-z]{12}['\"]\s?`,
	`LinkedInSecretKey`:      `(?i)linkedin(.{0,20})?['\"][0-9a-z]{16}['\"]\s?`,
	`WordPressVersion`:       `(?i)WordPress[/\s]v?\d+(\.\d+)?(\.\d+)?\s?`,
	`DrupalVersion`:          `(?i)Drupal[/\s]v?\d+(\.\d+)?(\.\d+)?\s?`,
	`JoomlaVersion`:          `(?i)Joomla!?[/\s]v?\d+(\.\d+)?(\.\d+)?\s?`,
	`MagentoVersion`:         `(?i)Magento[/\s]v?\d+(\.\d+)?(\.\d+)?\s?`,
	`UmbracoVersion`:         `(?i)Umbraco[/\s]v?\d+(\.\d+)?(\.\d+)?\s?`,
	`ImageFile`:              `([^\s]+(\.(?i)(jpg|png|gif|bmp|jpeg))\s?)`,
	`ServerHeader`:           `(?i)server: [\w\d/-:()$#! ]{1,35}\s?`,
	`StripeSecret`:           `(sk_live_[0-9a-zA-Z]{24}|rk_live_[0-9a-zA-Z]{24})`,
	`SQLiVars`:               `(?i)(id=[\w\d _\-+#@!:./]+\s?|select=[\w\d _\-+#@!:./]+\s?|report=[\w\d _\-+#@!:./]+\s?|role=[\w\d _\-+#@!:./]+\s?|update=[\w\d _\-+#@!:./]+\s?|query=[\w\d _\-+#@!:./]+\s?|user=[\w\d _\-+#@!:./]+\s?|name=[\w\d _\-+#@!:./]+\s?|sort=[\w\d _\-+#@!:./]+\s?|where=[\w\d _\-+#@!:./]+\s?|search=[\w\d _\-+#@!:./]+\s?|params=[\w\d _\-+#@!:./]+\s?|process=[\w\d _\-+#@!:./]+\s?|row=[\w\d _\-+#@!:./]+\s?|view=[\w\d _\-+#@!:./]+\s?|table=[\w\d _\-+#@!:./]+\s?|from=[\w\d _\-+#@!:./]+\s?|sel=[\w\d _\-+#@!:./]+\s?|results=[\w\d _\-+#@!:./]+\s?|sleep=[\w\d _\-+#@!:./]+\s?|fetch=[\w\d _\-+#@!:./]+\s?|order=[\w\d _\-+#@!:./]+\s?|keyword=[\w\d _\-+#@!:./]+\s?|column=[\w\d _\-+#@!:./]+\s?|field=[\w\d _\-+#@!:./]+\s?|delete=[\w\d _\-+#@!:./]+\s?|string=[\w\d _\-+#@!:./]+\s?|number=[\w\d _\-+#@!:./]+\s?|filter=[\w\d _\-+#@!:./]+\s?)`,
	`IDORVars`:               `(?i)(id=[\w\d _\-+#@!:./]+\s?|user=[\w\d _\-+#@!:./]+\s?|account=[\w\d _\-+#@!:./]+\s?|number=[\w\d _\-+#@!:./]+\s?|order=[\w\d _\-+#@!:./]+\s?|no=[\w\d _\-+#@!:./]+\s?|doc=[\w\d _\-+#@!:./]+\s?|key=[\w\d _\-+#@!:./]+\s?|email=[\w\d _\-+#@!:./]+\s?|group=[\w\d _\-+#@!:./]+\s?|profile=[\w\d _\-+#@!:./]+\s?|edit=[\w\d _\-+#@!:./]+\s?|report=[\w\d _\-+#@!:./]+\s?)`,
	`LFIVars`:                `(?i)(file=[\w\d _\-+#@!:./]+\s?|document=[\w\d _\-+#@!:./]+\s?|folder=[\w\d _\-+#@!:./]+\s?|root=[\w\d _\-+#@!:./]+\s?|path=[\w\d _\-+#@!:./]+\s?|pg=[\w\d _\-+#@!:./]+\s?|style=[\w\d _\-+#@!:./]+\s?|pdf=[\w\d _\-+#@!:./]+\s?|template=[\w\d _\-+#@!:./]+\s?|php_path=[\w\d _\-+#@!:./]+\s?|doc=[\w\d _\-+#@!:./]+\s?|page=[\w\d _\-+#@!:./]+\s?|name=[\w\d _\-+#@!:./]+\s?|cat=[\w\d _\-+#@!:./]+\s?|dir=[\w\d _\-+#@!:./]+\s?|action=[\w\d _\-+#@!:./]+\s?|board=[\w\d _\-+#@!:./]+\s?|date=[\w\d _\-+#@!:./]+\s?|detail=[\w\d _\-+#@!:./]+\s?|download=[\w\d _\-+#@!:./]+\s?|prefix=[\w\d _\-+#@!:./]+\s?|include=[\w\d _\-+#@!:./]+\s?|inc=[\w\d _\-+#@!:./]+\s?|locate=[\w\d _\-+#@!:./]+\s?|show=[\w\d _\-+#@!:./]+\s?|site=[\w\d _\-+#@!:./]+\s?|type=[\w\d _\-+#@!:./]+\s?|view=[\w\d _\-+#@!:./]+\s?|content=[\w\d _\-+#@!:./]+\s?|layout=[\w\d _\-+#@!:./]+\s?|mod=[\w\d _\-+#@!:./]+\s?|conf=[\w\d _\-+#@!:./]+\s?|url=[\w\d _\-+#@!:./]+\s?)`,
	`RCEVars`:                `(?i)(daemon=[\w\d _\-+#@!:./]+\s?|upload=[\w\d _\-+#@!:./]+\s?|dir=[\w\d _\-+#@!:./]+\s?|download=[\w\d _\-+#@!:./]+\s?|log=[\w\d _\-+#@!:./]+\s?|ip=[\w\d _\-+#@!:./]+\s?|cli=[\w\d _\-+#@!:./]+\s?|cmd=[\w\d _\-+#@!:./]+\s?|exec=[\w\d _\-+#@!:./]+\s?|command=[\w\d _\-+#@!:./]+\s?|execute=[\w\d _\-+#@!:./]+\s?|ping=[\w\d _\-+#@!:./]+\s?|query=[\w\d _\-+#@!:./]+\s?|jump=[\w\d _\-+#@!:./]+\s?|code=[\w\d _\-+#@!:./]+\s?|reg=[\w\d _\-+#@!:./]+\s?|do=[\w\d _\-+#@!:./]+\s?|func=[\w\d _\-+#@!:./]+\s?|arg=[\w\d _\-+#@!:./]+\s?|option=[\w\d _\-+#@!:./]+\s?|load=[\w\d _\-+#@!:./]+\s?|process=[\w\d _\-+#@!:./]+\s?|step=[\w\d _\-+#@!:./]+\s?|read=[\w\d _\-+#@!:./]+\s?|function[\w\d _\-+#@!:./]+\s?|req=[\w\d _\-+#@!:./]+\s?|feature=[\w\d _\-+#@!:./]+\s?|exe=[\w\d _\-+#@!:./]+\s?|module=[\w\d _\-+#@!:./]+\s?|payload=[\w\d _\-+#@!:./]+\s?|run=[\w\d _\-+#@!:./]+\s?|print=[\w\d _\-+#@!:./]+\s?)`,
	`OpenRedirectVars`:       `(?i)Lmage_url=[\w\d _\-+#@!:./]+\s?|Open=[\w\d _\-+#@!:./]+\s?|callback=[\w\d _\-+#@!:./]+\s?|checkout=[\w\d _\-+#@!:./]+\s?|checkout_url=[\w\d _\-+#@!:./]+\s?|continue=[\w\d _\-+#@!:./]+\s?|data=[\w\d _\-+#@!:./]+\s?|dest=[\w\d _\-+#@!:./]+\s?|destination=[\w\d _\-+#@!:./]+\s?|dir=[\w\d _\-+#@!:./]+\s?|domain=[\w\d _\-+#@!:./]+\s?|feed=[\w\d _\-+#@!:./]+\s?|file=[\w\d _\-+#@!:./]+\s?|file_name=[\w\d _\-+#@!:./]+\s?|file_url=[\w\d _\-+#@!:./]+\s?|folder=[\w\d _\-+#@!:./]+\s?|folder_url=[\w\d _\-+#@!:./]+\s?|forward=[\w\d _\-+#@!:./]+\s?|from_url=[\w\d _\-+#@!:./]+\s?|go=[\w\d _\-+#@!:./]+\s?|goto=[\w\d _\-+#@!:./]+\s?|host=[\w\d _\-+#@!:./]+\s?|html=[\w\d _\-+#@!:./]+\s?|image_url=[\w\d _\-+#@!:./]+\s?|img_url=[\w\d _\-+#@!:./]+\s?|load_file=[\w\d _\-+#@!:./]+\s?|load_url=[\w\d _\-+#@!:./]+\s?|login?to=[\w\d _\-+#@!:./]+\s?|login_url=[\w\d _\-+#@!:./]+\s?|logout=[\w\d _\-+#@!:./]+\s?|navigation=[\w\d _\-+#@!:./]+\s?|next=[\w\d _\-+#@!:./]+\s?|next_page=[\w\d _\-+#@!:./]+\s?|out=[\w\d _\-+#@!:./]+\s?|page=[\w\d _\-+#@!:./]+\s?|page_url=[\w\d _\-+#@!:./]+\s?|path=[\w\d _\-+#@!:./]+\s?|port=[\w\d _\-+#@!:./]+\s?|redir=[\w\d _\-+#@!:./]+\s?|redirect=[\w\d _\-+#@!:./]+\s?|redirect_to=[\w\d _\-+#@!:./]+\s?|redirect_uri=[\w\d _\-+#@!:./]+\s?|redirect_url=[\w\d _\-+#@!:./]+\s?|reference=[\w\d _\-+#@!:./]+\s?|return=[\w\d _\-+#@!:./]+\s?|returnTo=[\w\d _\-+#@!:./]+\s?|return_path=[\w\d _\-+#@!:./]+\s?|return_to=[\w\d _\-+#@!:./]+\s?|return_url=[\w\d _\-+#@!:./]+\s?|rt=[\w\d _\-+#@!:./]+\s?|rurl=[\w\d _\-+#@!:./]+\s?|show=[\w\d _\-+#@!:./]+\s?|site=[\w\d _\-+#@!:./]+\s?|target=[\w\d _\-+#@!:./]+\s?|to=[\w\d _\-+#@!:./]+\s?|uri=[\w\d _\-+#@!:./]+\s?|url=[\w\d _\-+#@!:./]+\s?|val=[\w\d _\-+#@!:./]+\s?|validate=[\w\d _\-+#@!:./]+\s?|view=[\w\d _\-+#@!:./]+\s?|window=[\w\d _\-+#@!:./]+\s?`,
}
