package strings

var Patterns = map[string]string{
	`HttpUrl`:              `\bhttps?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)($|\b)`,
	`AwsArn`:               `\barn:([^:\n]*):([^:\n]*):([^:\n]*):([^:\n]*):(([^:\/\n]*)[:\/])?(.*)($|\b)`,
	`AwsS3Bucket`:          `([a-z0-9.-]+\\.s3\\.amazonaws\\.com|//s3\\.amazonaws\\.com/[a-z0-9._-]+)`,
	`AwsKey`:               `([^A-Z0-9]|^)(AKIA|A3T|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{12,}`,
	`GitRepo`:              `\b(https?://)?github\.com(?:\/[^\s\/]+){2}($|\b)`,
	`Date`:                 `\b\d{2}[/-]\d{2}[/-]\d{2,4}($|\b)`,
	`Jwt`:                  `\beyJ[A-Za-z0-9-_=]+\.eyJ[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*($|\b)`,
	`UsAddress`:            `\b(\d+ [^,]+, [A-Z]{2} \d{5})($|\b)`,
	`IpAddrV4`:             `\b(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}\b($|\b)`,
	`IpAddrV6`:             `\b(?<![:.\w])(?:[A-F0-9]{1,4}:){7}[A-F0-9]{1,4}(?![:.\w])($|\b)`,
	`MacAddress`:           `([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})`,
	`Sid`:                  `\bS-\d-\d+-(\d+-){1,14}\d+\b($|\b)`,
	`Base32`:               `^(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}={6}|[A-Z2-7]{4}={4}|[A-Z2-7]{5}={3}|[A-Z2-7]{7}=)?$`,
	`Base64`:               `^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$`,
	`Md5`:                  `\b[a-f0-9]{32}($|\b)`,
	`Sha256`:               `\b[A-Fa-f0-9]{64}($|\b)`,
	`Sha512`:               `\b[A-Fa-f0-9]{128}($|\b)`,
	`Name`:                 `\b([a-zA-Z]{2,}\s[a-zA-Z]{1,}'?-?[a-zA-Z]{2,}\s?([a-zA-Z]{1,})?)($|\b)`,
	`EmailAddr`:            `^\S+@\S+\.\S+$`,
	`PhoneNumber`:          `^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}$`,
	`Ssn`:                  `^(?!666|000|9\\d{2})\\d{3}-(?!00)\\d{2}-(?!0{4})\\d{4}$`,
	`SlackToken`:           `xox[baprs]-([0-9a-zA-Z]{10,48})?-([0-9a-zA-Z]{10,48})?`,
	`SlackWebHook`:         `https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}`,
	`MailGunApiKey`:        `[0-9a-f]{32}-us[0-9]{1,2}`,
	`MailChimpKey`:         `[0-9a-f]{32}-us[0-9]{1,2}`,
	`GoogleApiKey`:         `AIza[0-9A-Za-z\\-_]{35}`,
	`FacebookToken`:        `EAACEdEose0cBA[0-9A-Za-z]+`,
	`Version`:              `\b(v(ersion)*\s*)([0-9]+)\.([0-9]+)\.([0-9]+)(?:\.([0-9]+))?\b$`,
	`LinuxPath`:            `^(/[^/ ]*)+/?$`,
	`TwilioApiKey`:         `^SK[0-9a-fA-F]{32}$`,
	`Password`:             `(pass(word|phrase)?|secret): \S+`,
	`UserName`:             `(user( ?name)?|login): \S+`,
	`Guid`:                 `[0-9a-fA-F]{8}-?[a-fA-F0-9]{4}-?[a-fA-F0-9]{4}-?[a-fA-F0-9]{4}-?[a-fA-F0-9]{12}`,
	`Isbn13`:               `(?:[\d]-?){12}[\dxX]`,
	`Isbn10`:               `(?:[\d]-?){9}[\dxX]`,
	`BtcAddress`:           `[13][a-km-zA-HJ-NP-Z1-9]{25,34}`,
	`CreditCard`:           `(?:(?:(?:\d{4}[- ]?){3}\d{4}|\d{15,16}))`,
	`McCreditCard`:         `5[1-5]\d{2}[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}`,
	`VisaCreditCard`:       `4\d{3}[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}`,
	`PowerShellPayload`:    `powershell.exe.*Hidden.*Enc`,
	`MsfPowerShellPayload`: `powershell.*FromBase64String.*IO.Compression.GzipStream`,
	`Coordinates`:          `^[-+]?([1-8]?\d(\.\d+)?|90(\.0+)?),\s*[-+]?(180(\.0+)?|((1[0-7]\d)|([1-9]?\d))(\.\d+)?)$`,
	`SquareAccessToken`:    `sqOatp-[0-9A-Za-z\\-_]{22}`,
	`SquareOauthSecret`:    `sq0csp-[ 0-9A-Za-z\\-_]{43}`,
	`AzureSubscriptionId`:  `^[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$`,
	`WapBssid`:             `([0-9A-F]{2}([:-]|$)){6}`,
	`WindowsVersion`:       `(Windows (7|8(\.1)?|3(\.1|\.0)|10|ME|XP|Vista|95|98|2000|1\.0[1-4]|2\.(03|1[0|1])))$`,
	`EnvironmentVariable`:  `^([A-Z]+=\w+)$`,
	`NetworkShare`:         `^(\\)(\\[\w\.-_]+){2,}(\\?)$`,
}
